var Contests=[
    {
        name:"blah",
        Leaderboard:{
            top5:[
                {
                    name:"swathi",
                    score:100
                },
                {
                    name:"swetha",
                    score:90
                },
                {
                    name:"Datta",
                    score:50
                },
                {
                    name:"Prawn",
                    score:42
                },
                {
                    name:"Sruthi",
                    score:41
                }
            ],
            score:50,
            rank:3
        },
        chat:[
            {
                sender:"swathi",
                message:"hello",
                time:"12:30"
            },
            {
                sender:"swetha",
                message:"hi",
                time:"12:30"
            },
            {
                sender:"Datta",
                message:"vanakkam",
                time:"12:30"
            },
            {
                sender:"prwan",
                message:"namaste",
                time:"12:30"
            },
            {
                sender:"swathi",
                message:"hello",
                time:"12:30"
            },
            {
                sender:"swetha",
                message:"hi",
                time:"12:30"
            },
            {
                sender:"Datta",
                message:"vanakkam",
                time:"12:30"
            },
            {
                sender:"prwan",
                message:"namaste",
                time:"12:30"
            }
        ]
    },
    {
        name:"blah blah",
        Leaderboard:{
            top5:[
                {
                    name:"swathi",
                    score:100
                },
                {
                    name:"swetha",
                    score:90
                },
                {
                    name:"Datta",
                    score:50
                },
                {
                    name:"Prawn",
                    score:42
                },
                {
                    name:"Sruthi",
                    score:41
                }
            ],
            score:50,
            rank:3
        },
        chat:[
            {
                sender:"swathi",
                message:"hello",
                time:"12:30"
            },
            {
                sender:"swetha",
                message:"hi",
                time:"12:30"
            },
            {
                sender:"Datta",
                message:"vanakkam",
                time:"12:30"
            },
            {
                sender:"prwan",
                message:"namaste",
                time:"12:30"
            }
        ]
    },
];

export default Contests;